logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: adm0n2
    url: jdbc:postgresql://localhost:5432/consultorio_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update